IF EXIST "DELTARUNE-9_Original.pcm" (
	RENAME "DELTARUNE-9.pcm" "DELTARUNE-9_alt.pcm"
	RENAME "DELTARUNE-9_Original.pcm" "DELTARUNE-9.pcm"
) ELSE IF EXIST "DELTARUNE-9_alt.pcm" (
	RENAME "DELTARUNE-9.pcm" "DELTARUNE-9_Original.pcm"
	RENAME "DELTARUNE-9_alt.pcm" "DELTARUNE-9.pcm"
)

IF EXIST "DELTARUNE-16_Original.pcm" (
	RENAME "DELTARUNE-16.pcm" "DELTARUNE-16_alt.pcm"
	RENAME "DELTARUNE-16_Original.pcm" "DELTARUNE-16.pcm"
) ELSE IF EXIST "DELTARUNE-16_alt.pcm" (
	RENAME "DELTARUNE-16.pcm" "DELTARUNE-16_Original.pcm"
	RENAME "DELTARUNE-16_alt.pcm" "DELTARUNE-16.pcm"
)

IF EXIST "DELTARUNE-37_Original.pcm" (
	RENAME "DELTARUNE-37.pcm" "DELTARUNE-37_alt.pcm"
	RENAME "DELTARUNE-37_Original.pcm" "DELTARUNE-37.pcm"
) ELSE IF EXIST "DELTARUNE-37_alt.pcm" (
	RENAME "DELTARUNE-37.pcm" "DELTARUNE-37_Original.pcm"
	RENAME "DELTARUNE-37_alt.pcm" "DELTARUNE-37.pcm"
)

IF EXIST "DELTARUNE-46_Original.pcm" (
	RENAME "DELTARUNE-46.pcm" "DELTARUNE-46_alt.pcm"
	RENAME "DELTARUNE-46_Original.pcm" "DELTARUNE-46.pcm"
) ELSE IF EXIST "DELTARUNE-46_alt.pcm" (
	RENAME "DELTARUNE-46.pcm" "DELTARUNE-46_Original.pcm"
	RENAME "DELTARUNE-46_alt.pcm" "DELTARUNE-46.pcm"
)

IF EXIST "DELTARUNE-59_Original.pcm" (
	RENAME "DELTARUNE-59.pcm" "DELTARUNE-59_alt.pcm"
	RENAME "DELTARUNE-59_Original.pcm" "DELTARUNE-59.pcm"
) ELSE IF EXIST "DELTARUNE-59_alt.pcm" (
	RENAME "DELTARUNE-59.pcm" "DELTARUNE-59_Original.pcm"
	RENAME "DELTARUNE-59_alt.pcm" "DELTARUNE-59.pcm"
)

IF EXIST "DELTARUNE-61_Original.pcm" (
	RENAME "DELTARUNE-61.pcm" "DELTARUNE-61_alt.pcm"
	RENAME "DELTARUNE-61_Original.pcm" "DELTARUNE-61.pcm"
) ELSE IF EXIST "DELTARUNE-61_alt.pcm" (
	RENAME "DELTARUNE-61.pcm" "DELTARUNE-61_Original.pcm"
	RENAME "DELTARUNE-61_alt.pcm" "DELTARUNE-61.pcm"
)

